include(CMakeFindDependencyMacro)
find_dependency(Protobuf)
find_dependency(ProtobufComm)
find_dependency(spdlog)
find_dependency(clips)
include("${CMAKE_CURRENT_LIST_DIR}/ClipsProtobufTargets.cmake")
